services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "${RAM:-4}G"
      VERSION: "${VERSION:-LATEST}"
      MODE: "${MODE:-creative}"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
